// C/C++ includes header
#include <cmath>         // include to get: exp(), abs(), M_PI(), ...
#include <fstream>       // include to get: fopen(), fclose(), ...
#include <iostream>      // include to get: cout (unformatted stream output)
#include <sstream>       // include to get: stringstream
#include <string.h>      // include to get: strcpy
#include <stdlib.h>      // include to get: exit, EXIT_FAILURE...
#include <iomanip>       // include to get  formated text 
#include <vector>        // include to get: vector<double> vectorName...
#include <map>           // include to get: map<init,double> mapName...
#include <iterator>      // include to get: map<init,double>:: iterator it...

// Namespaces
using namespace std;     // avoid std::<function_name
