// C/C++ includes
#include <cmath>         // include to get: exp(), abs(), M_PI(), ...
#include <fstream>       // include to get: fopen(), fclose(), ...
#include <iostream>      // include to get: cout (unformatted stream output)
#include <sstream>       // include to get: stringstream
#include <string.h>      // include to get: strcpy
#include <stdlib.h>      // include to get: exit, EXIT_FAILURE...
#include <vector>        // include to get: vectors...
// Namespaces
using namespace std;     // avoid std::<functionname>
